from typing import Any, Optional

xrange = range

class PBKDF2:
    def __init__(self, passphrase: Any, salt: Any, iterations: int = ..., digestmodule: Any = ..., macmodule: Any = ...) -> None: ...
    def read(self, bytes: Any): ...
    def hexread(self, octets: Any): ...
    closed: bool = ...
    def close(self) -> None: ...

def crypt(word: Any, salt: Optional[Any] = ..., iterations: Optional[Any] = ...): ...
