from typing import Any

__metaclass__ = type

class KeyringError(Exception): ...
class PasswordSetError(KeyringError): ...
class PasswordDeleteError(KeyringError): ...
class InitError(KeyringError): ...
class KeyringLocked(KeyringError): ...
class NoKeyringError(KeyringError, RuntimeError): ...

class ExceptionRaisedContext:
    ExpectedException: Any = ...
    exc_info: Any = ...
    def __init__(self, ExpectedException: Any = ...) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *exc_info: Any): ...

class ExceptionInfo:
    def __init__(self, *info: Any) -> None: ...
    def __bool__(self): ...
    __nonzero__: Any = ...
