name: "Pull Request Docs Check"
on: 
- pull_request
- push

jobs:
  docs:

    strategy:
      matrix:
        python-version: ["3.12"]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    - uses: ammaraskar/sphinx-action@7.1.2
      with:
        docs-folder: "docs/"
        pre-build-command: python -m pip install '.[docs]'
